version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: helloexpress:latest
    container_name: helloexpress.backend
    environment:
      NODE_ENV: "development"
    ports:
      - "3100:3000"
      - "9229:9229"
